// 自动生成的职业与本职技能映射（部分技能key需与skillTranslations一致）
const professionSkillMapping = {
  "自定义职业": [],
  "会计师": ["accounting", "law", "libraryUse", "listen", "persuade", "spotHidden", "special1", "special2"],
  "杂技演员": ["climb", "dodge", "jump", "throw", "spotHidden", "swim", "special1", "special2"],
  "演员-戏剧演员": ["artCraft1", "disguise", "fighting1", "history", "charm", "fastTalk", "intimidate", "persuade", "psychology", "special1"],
  "演员-电影演员": ["artCraft1", "disguise", "driveAuto", "charm", "fastTalk", "intimidate", "persuade", "psychology", "special1", "special2"],
  "事务所侦探、保安": ["charm", "fastTalk", "intimidate", "persuade", "fighting", "firearms", "law", "libraryUse", "psychology", "stealth", "track"],
  "精神病医生（古典）": ["law", "listen", "medicine", "languageOther", "psychoanalysis", "psychology", "science"],
  "动物训练师": ["jump", "listen", "naturalWorld", "psychology", "science9", "stealth", "track", "special1"],
  "文物学家（原作向）": ["appraise", "artCraft1", "history", "libraryUse", "language1", "charm", "fastTalk", "intimidate", "persuade", "spotHidden", "special1"],
  "古董商": ["accounting", "appraise", "driveAuto", "charm", "fastTalk", "intimidate", "persuade", "history", "libraryUse", "navigate"],
  "考古学家（原作向）": ["appraise", "archaeology", "history", "language1", "libraryUse", "spotHidden", "mechanicalRepair", "navigate", "science1"],
  "建筑师": ["accounting", "artCraft18", "law", "nativeLanguage", "libraryUse", "persuade", "psychology", "science4"],
  "艺术家": ["artCraft2", "history", "naturalWorld", "charm", "fastTalk", "intimidate", "persuade", "language1", "psychology", "spotHidden", "special1", "special2"],
  "精神病院看护": ["dodge", "fighting1", "firstAid", "charm", "fastTalk", "intimidate", "persuade", "listen", "psychology", "stealth"],
  "运动员": ["climb", "jump", "fighting1", "ride", "charm", "fastTalk", "intimidate", "persuade", "swim", "throw", "special1"],
  "作家（原作向）": ["artCraft5", "history", "libraryUse", "naturalWorld", "occult", "language1", "nativeLanguage", "psychology", "special1"],
  "酒保": ["accounting", "charm", "fastTalk", "intimidate", "persuade", "fighting", "listen", "psychology", "spotHidden", "special1"],
  "猎人": ["firearms1", "listen", "spotHidden", "naturalWorld", "navigate", "language1", "survival", "science3", "science8", "stealth", "track"],
  "书商": ["accounting", "appraise", "driveAuto", "history", "libraryUse", "ownLanguage", "languageOther", "charm", "fastTalk", "intimidate", "persuade"],
  "赏金猎人": ["driveAuto", "electricalRepair", "fighting1", "firearms1", "charm", "fastTalk", "intimidate", "persuade", "law", "psychology", "track", "stealth"],
  "拳击手、摔跤手": ["dodge", "fighting1", "intimidate", "jump", "psychology", "spotHidden", "special1", "special2"],
  "管家、男仆、女仆": ["accounting", "appraise", "artCraft", "firstAid", "listen", "languageOther", "psychology", "spotHidden", "special1"],
  "神职人员": ["accounting", "history", "libraryUse", "listen", "language1", "charm", "fastTalk", "intimidate", "persuade", "psychology", "special1"],
  "程序员、电子工程师（现代）": ["libraryUse", "electricalRepair", "libraryUse", "science4", "spotHidden", "special1", "special2"],
  "黑客/骇客（现代）": ["libraryUse", "electricalRepair", "libraryUse", "spotHidden", "charm", "fastTalk", "intimidate", "persuade", "special1", "special2"],
  "牛仔": ["dodge", "fighting1", "firearms1", "firstAid", "naturalWorld", "jump", "ride", "survival", "throw", "track"],
  "工匠": ["accounting", "artCraft2", "mechanicalRepair", "naturalWorld", "spotHidden", "special1", "special2"],
  "罪犯-刺客": ["disguise", "electricalRepair", "fighting1", "firearms1", "locksmith", "mechanicalRepair", "stealth", "psychology"],
  "罪犯-银行劫匪": ["driveAuto", "electricalRepair", "mechanicalRepair", "fighting1", "firearms1", "intimidate", "locksmith", "operateHeavyMachinery", "special1"],
  "罪犯-打手、暴徒": ["driveAuto", "fighting1", "firearms1", "charm", "fastTalk", "intimidate", "persuade", "psychology", "stealth", "spotHidden"],
  "罪犯-窃贼": ["appraise", "climb", "electricalRepair", "mechanicalRepair", "listen", "locksmith", "sleightOfHand", "stealth", "spotHidden"],
  "罪犯-欺诈师": ["appraise", "artCraft2", "law", "language1", "listen", "charm", "fastTalk", "intimidate", "persuade", "psychology", "sleightOfHand"],
  "罪犯-独行罪犯": ["artCraft2", "disguise", "appraise", "charm", "fastTalk", "intimidate", "persuade", "fighting1", "firearms1", "locksmith", "mechanicalRepair", "stealth", "psychology", "spotHidden"],
  "罪犯-女飞贼（古典）": ["artCraft2", "charm", "fastTalk", "intimidate", "persuade", "fighting1", "firearms1", "driveAuto", "listen", "stealth", "special1"],
  "罪犯-赃物贩子": ["accounting", "appraise", "artCraft4", "history", "charm", "fastTalk", "intimidate", "persuade", "libraryUse", "spotHidden", "special1"],
  "罪犯-赝造者": ["accounting", "appraise", "artCraft4", "history", "libraryUse", "spotHidden", "sleightOfHand", "special1"],
  "罪犯-走私者": ["firearms1", "listen", "navigate", "charm", "fastTalk", "intimidate", "persuade", "driveAuto", "pilot", "psychology", "sleightOfHand", "spotHidden"],
  "罪犯-混混": ["climb", "charm", "fastTalk", "intimidate", "persuade", "fighting1", "firearms1", "jump", "sleightOfHand", "stealth", "throw"],
  "教团首领": ["accounting", "charm", "fastTalk", "intimidate", "persuade", "occult", "psychology", "spotHidden", "special1", "special2"],
  "除魅师（现代）": ["charm", "fastTalk", "intimidate", "persuade", "driveAuto", "fighting", "firearms", "history", "occult", "psychology", "stealth"],
  "设计师": ["accounting", "artCraftPhotography", "artCraft", "computerUse", "libraryUse", "mechanicalRepair", "psychology", "spotHidden", "special1"],
  "业余艺术爱好者（原作向）": ["artCraft", "firearms", "languageOther", "ride", "charm", "fastTalk", "intimidate", "persuade", "special1", "special2", "special3"],
  "潜水员": ["diving", "firstAid", "mechanicalRepair", "pilotBoat", "scienceBio", "spotHidden", "swim", "special1"],
  "医生（原作向）": ["firstAid", "medicine", "languageLatin", "psychology", "scienceBio", "sciencePharmacy", "special1", "special2"],
  "流浪者": ["climb", "jump", "listen", "navigate", "charm", "fastTalk", "intimidate", "persuade", "stealth", "special1", "special2"],
  "司机-私人司机": ["driveAuto", "charm", "fastTalk", "intimidate", "persuade", "listen", "mechanicalRepair", "navigate", "spotHidden", "special1"],
  "司机-司机": ["accounting", "driveAuto", "listen", "charm", "fastTalk", "intimidate", "persuade", "mechanicalRepair", "navigate", "psychology", "special1"],
  "司机-出租车司机": ["accounting", "driveAuto", "electricalRepair", "fastTalk", "mechanicalRepair", "navigate", "spotHidden", "special1"],
  "编辑": ["accounting", "history", "ownLanguage", "charm", "fastTalk", "intimidate", "persuade", "psychology", "spotHidden", "special1"],
  "政府官员": ["charm", "history", "intimidate", "fastTalk", "listen", "ownLanguage", "persuade", "psychology"],
  "工程师": ["artCraftDrafting", "electricalRepair", "libraryUse", "mechanicalRepair", "operateHeavy", "scienceEngineering", "sciencePhysics", "special1"],
  "艺人": ["artCraftPerformance", "disguise", "charm", "fastTalk", "intimidate", "persuade", "listen", "psychology", "special1", "special2"],
  "探险家（古典）": ["climb", "swim", "firearms", "history", "jump", "naturalWorld", "navigate", "languageOther", "survival"],
  "农民": ["artCraftFarming", "driveAuto", "charm", "fastTalk", "intimidate", "persuade", "mechanicalRepair", "naturalWorld", "operateHeavy", "track", "special1"],
  "联邦探员": ["driveAuto", "fighting", "firearms", "law", "persuade", "stealth", "spotHidden", "special1"],
  "消防员": ["climb", "dodge", "driveAuto", "firstAid", "jump", "mechanicalRepair", "operateHeavy", "throw"],
  "驻外记者": ["history", "languageOther", "ownLanguage", "listen", "charm", "fastTalk", "intimidate", "persuade", "psychology", "special1"],
  "法医": ["languageLatin", "libraryUse", "medicine", "persuade", "scienceBio", "scienceForensics", "sciencePharmacy", "spotHidden"],
  "赌徒": ["accounting", "artCraftPerformance", "charm", "fastTalk", "intimidate", "persuade", "listen", "psychology", "sleightOfHand", "spotHidden"],
  "黑帮-黑帮老大": ["fighting", "firearms", "law", "listen", "charm", "fastTalk", "intimidate", "persuade", "psychology", "spotHidden"],
  "黑帮-马仔": ["fighting", "firearms", "stealth", "intimidate", "persuade", "charm", "fastTalk", "psychology", "spotHidden", "special1"],
  "绅士、淑女": ["charm", "persuade", "intimidate", "ownLanguage", "history", "psychology", "special1", "special2"],
  "游民": ["stealth", "climb", "jump", "listen", "spotHidden", "fastTalk", "intimidate", "persuade", "special1"],
  "勤杂护工": ["firstAid", "psychology", "listen", "spotHidden", "charm", "persuade", "special1", "special2"],
  "记者(原作向)-调查记者": ["libraryUse", "history", "ownLanguage", "psychology", "spotHidden", "charm", "fastTalk", "persuade", "special1"],
  "记者(原作向)-通讯记者": ["ownLanguage", "libraryUse", "history", "psychology", "charm", "fastTalk", "persuade", "special1"],
  "法官": ["law", "psychology", "persuade", "intimidate", "ownLanguage", "history", "special1", "special2"],
  "实验室助理": ["scienceChemistry", "scienceBiology", "libraryUse", "operateHeavy", "mechanicalRepair", "computerUse", "firstAid"],
  "工人-非熟练工人": ["climb", "jump", "mechanicalRepair", "operateHeavy", "fighting", "listen", "spotHidden"],
  "工人-伐木工": ["climb", "fighting", "mechanicalRepair", "operateHeavy", "survival", "naturalWorld", "firstAid"],
  "工人-矿工": ["climb", "mechanicalRepair", "operateHeavy", "survival", "navigate", "spotHidden"],
  "律师": ["law", "persuade", "psychology", "ownLanguage", "charm", "fastTalk", "intimidate", "libraryUse"],
  "图书馆管理员（原作向）": ["libraryUse", "history", "ownLanguage", "psychology", "appraise"],
  "技师": ["mechanicalRepair", "electricalRepair", "computerUse", "scienceEngineering", "operateHeavy"],
  "军官": ["navigate", "fighting", "firearms", "persuade", "intimidate", "psychology", "law", "leadership"],
  "传教士": ["charm", "persuade", "psychology", "history", "languageOther", "theology"],
  "登山家": ["climb", "jump", "navigate", "survival", "naturalWorld", "firstAid", "spotHidden"],
  "博物馆管理员": ["history", "libraryUse", "appraise", "psychology", "artCraft"],
  "音乐家": ["artCraftMusic", "charm", "persuade", "psychology", "artCraft"],
  "护士": ["firstAid", "medicine", "psychology", "listen", "biology"],
  "神秘学家": ["occult", "history", "libraryUse", "psychology", "anthropology"],
  "旅行家": ["navigate", "languageOther", "survival", "naturalWorld", "appraise"],
  "超心理学家": ["psychology", "occult", "science", "anthropology"],
  "药剂师": ["sciencePharmacy", "medicine", "psychology", "chemistry"],
  "摄影师-摄影师": ["artCraftPhotography", "spotHidden", "psychology", "artCraft"],
  "摄影师-摄影记者": ["artCraftPhotography", "libraryUse", "spotHidden", "charm", "fastTalk", "artCraft"],
  "飞行员-飞行员": ["pilot", "navigate", "mechanicalRepair", "spotHidden", "operateHeavy"],
  "飞行员-特技飞行员（古典）": ["pilot", "navigate", "mechanicalRepair", "climb", "jump", "operateHeavy"],
  "警方(原作向)-警探": ["law", "psychology", "spotHidden", "fighting", "firearms", "libraryUse"],
  "警方(原作向)-巡警": ["fighting", "firearms", "spotHidden", "psychology", "law"],
  "私家侦探": ["libraryUse", "spotHidden", "psychology", "law", "fighting", "disguise"],
  "教授（原作向）": ["ownLanguage", "libraryUse", "history", "psychology", "science"],
  "淘金客": ["appraise", "navigate", "survival", "spotHidden"],
  "性工作者": ["charm", "persuade", "psychology", "fastTalk"],
  "精神病学家": ["psychoanalysis", "psychology", "medicine", "biology"],
  "心理学家、精神分析学家": ["psychoanalysis", "psychology", "biology"],
  "研究员": ["science", "libraryUse", "psychology"],
  "海员-军舰海员": ["navigate", "mechanicalRepair", "fighting", "operateHeavy"],
  "海员-民船海员": ["navigate", "mechanicalRepair", "operateHeavy"],
  "推销员": ["charm", "persuade", "fastTalk", "psychology", "accounting"],
  "科学家": ["science", "libraryUse", "psychology", "biology"],
  "秘书": ["accounting", "ownLanguage", "psychology", "libraryUse"],
  "店老板": ["accounting", "appraise", "charm", "persuade", "psychology"],
  "士兵、海军陆战队士兵": ["fighting", "firearms", "navigate", "survival", "firstAid"],
  "间谍": ["disguise", "stealth", "psychology", "fastTalk"],
  "学生、实习生": ["libraryUse", "ownLanguage", "psychology"],
  "替身演员": ["artPerformance", "disguise", "fighting", "jump"],
  "部落成员": ["survival", "naturalWorld", "track"],
  "殡葬师": ["psychology", "firstAid", "biology"],
  "工会活动家": ["persuade", "intimidate", "psychology", "law"],
  "服务生": ["charm", "persuade", "psychology", "listen"],
  "白领工人-职员、主管": ["accounting", "ownLanguage", "psychology", "libraryUse"],
  "白领工人-中高层管理人员": ["accounting", "ownLanguage", "psychology", "persuade", "leadership"],
  "狂热者": ["occult", "persuade", "intimidate", "psychology", "anthropology"],
  "饲养员": ["naturalWorld", "scienceAnimal", "biology"],
  "大使": ["charm", "persuade", "ownLanguage", "languageOther", "psychology"],
  "运动员（游泳/潜水）": ["swim", "dodge", "jump", "climb"],
  "运动员（高尔夫）": ["artCraftGolf", "psychology"],
  "运动员（网球）": ["artCraftTennis", "psychology"],
  "运动员（田径）": ["climb", "jump", "throw", "psychology"],
  "发言人": ["charm", "persuade", "ownLanguage", "psychology"],
  "保释担保人": ["law", "persuade", "intimidate", "psychology"],
  "神职人员(天主教牧师)": ["history", "libraryUse", "charm", "persuade", "psychology", "theology"],
  "神职人员(新教牧师)": ["history", "libraryUse", "charm", "persuade", "psychology", "theology"],
  "神职人员(犹太教拉比)": ["history", "libraryUse", "charm", "persuade", "psychology", "theology"],
  "专栏作家": ["ownLanguage", "libraryUse", "history", "psychology"],
  "社会主义者/激进主义者": ["persuade", "intimidate", "psychology", "law"],
  "撰稿人": ["ownLanguage", "libraryUse", "history", "psychology"],
  "罪犯（赌博庄家）": ["sleightOfHand", "charm", "fastTalk", "intimidate", "persuade", "accounting"],
  "罪犯（放高利贷者）": ["accounting", "intimidate", "persuade", "law"],
  "罪犯（扒手）": ["sleightOfHand", "stealth", "spotHidden", "disguise"],
  "罪犯（地下钱庄）": ["accounting", "appraise", "law"],
  "罪犯（黑律师）": ["law", "accounting", "persuade"],
  "牙医": ["medicine", "science", "biology"],
  "外科医生/内科医生": ["medicine", "science", "biology"],
  "整形医生": ["medicine", "science", "biology"],
  "司机-公交司机": ["driveAuto", "navigate", "mechanicalRepair"],
  "实地调研员": ["libraryUse", "psychology", "appraise"],
  "电影摄制人员": ["artCraftPhotography", "artCraft"],
  "司法科学家": ["scienceForensics", "law", "psychology"],
  "运动经理": ["persuade", "psychology", "leadership"],
  "商船队船员": ["navigate", "mechanicalRepair", "operateHeavy"],
  "古典音乐家": ["artCraftMusic", "artCraft"],
  "赛车手/ 赛艇手": ["driveAuto", "pilotBoat", "mechanicalRepair"],
  "电台播音员": ["ownLanguage", "charm", "psychology"],
  "推销员（圣经推销员）": ["charm", "persuade", "psychology"],
  "推销员（旅行推销员）": ["charm", "persuade", "psychology"],
  "小企业家": ["accounting", "appraise", "persuade"],
  "舞台工作人员": ["artCraft", "mechanicalRepair"],
  "证券经纪人": ["accounting", "persuade", "psychology"],
  "勘测员": ["navigate", "appraise", "science"],
  "电话接线员": ["listen", "psychology"],
  "星探": ["spotHidden", "charm", "psychology"],
  "医疗技术员": ["firstAid", "science", "biology"],
  "队医": ["firstAid", "medicine", "biology"],
  "寻宝猎人": ["appraise", "navigate", "spotHidden"],
  "西部治安官": ["law", "fighting", "firearms", "psychology"],
  "暴走族": ["driveAuto", "fighting", "intimidate"],
  "神职人员(和尚,尼姑)": ["history", "libraryUse", "charm", "persuade", "psychology", "theology"],
  "神职人员(神官,巫女)": ["history", "libraryUse", "charm", "persuade", "psychology", "theology"],
  "风水师": ["occult", "psychology", "anthropology"],
  "家传降妖人": ["occult", "psychology", "anthropology"],
  "高中生(教育60以下)": ["libraryUse", "ownLanguage", "psychology"],
  "市子（盲人）": ["listen", "psychology"],
  "言灵师/阴阳师": ["occult", "psychology", "anthropology"],
  "炼丹师": ["science", "occult", "chemistry"],
  "外语教师": ["languageOther", "ownLanguage", "psychology"],
  "非法移民": ["stealth", "survival", "disguise"],
  "相扑力士(SIZ>80,STR>70)": ["fighting", "jump", "intimidate"],
  "渔民": ["swim", "navigate", "naturalWorld", "biology"],
  "心理治疗师": ["psychology", "biology"],
  "女学生": ["libraryUse", "ownLanguage", "psychology"],
  "寄居学生": ["libraryUse", "ownLanguage", "psychology"],
  "动物辅助治疗师": ["psychology", "scienceAnimal", "biology"],
  "急诊医生/救援队员": ["firstAid", "medicine", "biology"],
  "密医": ["medicine", "biology"],
  "科学搜查研究员": ["scienceForensics", "psychology", "biology"],
  "山岳救援队员": ["climb", "firstAid", "biology"],
  "舞者": ["artCraftDance", "artCraft"],
  "服装设计师": ["artCraft", "psychology"],
  "海上自卫队员": ["navigate", "mechanicalRepair", "operateHeavy"],
  "海警": ["navigate", "mechanicalRepair", "operateHeavy"],
  "陆上自卫队员": ["fighting", "mechanicalRepair", "operateHeavy"],
  "私人军事公司成员": ["fighting", "firearms", "intimidate"],
  "冒险家教授": ["history", "libraryUse", "psychology", "science"],
  "评论家": ["ownLanguage", "history", "psychology"],
  "偶像": ["artCraftPerformance", "charm", "psychology"],
  "歌手": ["artCraftMusic", "charm", "psychology"],
  "搞笑艺人": ["artCraftPerformance", "charm", "psychology"],
  "运动员艺人": ["artCraftPerformance", "fighting", "psychology"],
  "播音员": ["ownLanguage", "charm", "psychology"],
  "主持人": ["ownLanguage", "charm", "psychology"],
  "电视解说员": ["ownLanguage", "charm", "psychology"],
  "网络明星": ["ownLanguage", "charm", "psychology"],
  "经纪人": ["persuade", "charm", "psychology"],
  "捉鬼人": ["occult", "psychology", "anthropology"],
  "占卜师、灵媒师": ["occult", "psychology", "anthropology"],
  "机械师": ["mechanicalRepair", "operateHeavy"],
  "厨师": ["artCraftCooking", "psychology"],
  "网络犯罪者": ["computerUse", "stealth", "disguise"],
  "佣兵": ["fighting", "firearms", "intimidate"],
  "自宅警备员": ["computerUse", "psychology"],
  "壮汉保镖": ["fighting", "intimidate", "psychology"],
  "游戏测试员": ["computerUse", "psychology"],
  "交际花": ["charm", "persuade", "psychology"],
  "考古学家": ["archaeology", "history", "libraryUse", "languageOther", "appraise", "spotHidden", "navigate", "special1"],
  "贵族": ["charm", "persuade", "intimidate", "ownLanguage", "history", "psychology", "special1", "special2"],
  "艺术家": ["artCraft", "history", "psychology", "charm", "special1", "special2"],
  "作家": ["artCraftLiterature", "history", "libraryUse", "ownLanguage", "psychology", "special1", "special2"],
  "马车夫": ["driveAuto", "navigate", "mechanicalRepair", "special1", "special2"],
  "牧师": ["history", "libraryUse", "charm", "persuade", "psychology", "special1", "special2"],
  "咨询侦探": ["libraryUse", "spotHidden", "psychology", "law", "fighting", "special1", "special2"],
  "工匠": ["artCraft", "mechanicalRepair", "appraise", "special1", "special2"],
  "罪犯": ["stealth", "fighting", "firearms", "locksmith", "sleightOfHand", "special1", "special2"],
  "业余艺术爱好者": ["artCraft", "charm", "special1", "special2"],
  "艺人": ["artCraftPerformance", "charm", "special1", "special2"],
  "退役军官": ["navigate", "fighting", "firearms", "persuade", "intimidate", "psychology", "special1", "special2"],
  "探险家": ["climb", "swim", "firearms", "history", "jump", "naturalWorld", "navigate", "languageOther", "survival"],
  "私家侦探": ["libraryUse", "spotHidden", "psychology", "law", "fighting", "special1", "special2"],
  "记者": ["libraryUse", "history", "ownLanguage", "psychology", "spotHidden", "charm", "fastTalk", "persuade", "special1"],
  "劳工": ["climb", "jump", "mechanicalRepair", "operateHeavy", "fighting", "special1", "special2"],
  "律师": ["law", "persuade", "psychology", "ownLanguage", "charm", "fastTalk", "intimidate", "special1"],
  "医生": ["firstAid", "medicine", "psychology", "scienceBio", "sciencePharmacy", "special1", "special2"],
  "警察": ["law", "psychology", "spotHidden", "fighting", "firearms", "special1", "special2"],
  "教授/学者": ["ownLanguage", "libraryUse", "history", "psychology", "special1", "special2"],
  "科学家": ["science", "libraryUse", "psychology", "special1", "special2"],
  "佣人": ["accounting", "appraise", "artCraft", "firstAid", "listen", "languageOther", "psychology", "spotHidden", "special1"],
  "店主": ["accounting", "appraise", "charm", "persuade", "special1", "special2"],
  "士兵": ["fighting", "firearms", "navigate", "survival", "special1", "special2"],
  "密探": ["disguise", "stealth", "psychology", "special1", "special2"],
};

export default professionSkillMapping;